name: scroll_animate
description: A new Flutter project.
version: 1.0.0+1
homepage: https://github.com/MichaelRFairhurst/scroll_animate

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
